TO-DO-List/TO-DO-List/Controllers/CategoryController.cs
using DataAccess.Contracts;
using DataStructure.Models;
using Microsoft.AspNetCore.Mvc;
using TO_DO_List.Attributes;
using TO_DO_List.ViewModels;

namespace TO_DO_List.Controllers
{
    public class CategoryController : Controller
    {
        private readonly IBaseRepository baseRepository;

        public CategoryController(IBaseRepository baseRepository)
        {
            this.baseRepository = baseRepository;
        }

        [HttpGet]
        [Authenticate]
        public IActionResult Index()
        {
            return View(baseRepository.GetAll<Category>().Where(x => x.User!.ID == HttpContext.Session.GetInt32("UserID")!.Value));
        }

        [Authenticate]
        [HttpGet]
        public IActionResult Details(int id)
        {
            return View(baseRepository.GetByID<Category>(id));
        }

        [Authenticate]
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [Authenticate]
        [HttpPost]
        public IActionResult Create(CategoryViewModel categoryViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(categoryViewModel);
            }

            Category category = new Category()
            {
                Name = categoryViewModel.Name,
                User = baseRepository.GetByID<User>(HttpContext.Session.GetInt32("UserID")!.Value)
            };
            baseRepository.Create<Category>(category);

            return RedirectToAction(nameof(Index));
        }

        [Authenticate]
        [HttpGet]
        public IActionResult Edit(int id)
        {
            Category category = baseRepository.GetByID<Category>(id);
            return View(new CategoryViewModel()
            {
                ID = category.ID,
                Name = category.Name
            });
        }

        [Authenticate]
        [HttpPost]
        public IActionResult Edit(CategoryViewModel categoryViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(categoryViewModel);
            }
            Category category = baseRepository.GetByID<Category>(categoryViewModel.ID);
            category.Name = categoryViewModel.Name;
            baseRepository.Update<Category>(category);
            return RedirectToAction(nameof(Index));
        }

        [Authenticate]
        [HttpGet]
        public IActionResult Delete(int? id)
        {
            return View(baseRepository.GetByID<Category>(id.Value));
        }

        [Authenticate]
        [HttpPost]
        public IActionResult Delete(int id)
        {
            baseRepository.Delete<Category>(baseRepository.GetByID<Category>(id));
            return RedirectToAction(nameof(Index));
        }
    }
}

TO-DO-List/TO-DO-List/Controllers/UserController.cs
using DataStructure.Models;
using Microsoft.AspNetCore.Mvc;
using DataAccess.Contracts;
using TO_DO_List.Services.Contracts;
using TO_DO_List.ViewModels;
using TO_DO_List.Attributes;

namespace TO_DO_List.Controllers
{
    public class UserController : Controller
    {
        private readonly IBaseRepository baseRepository;
        private readonly IUserService userService;
        public UserController(IBaseRepository baseRepository,
            IUserService userService)
        {
            this.baseRepository = baseRepository;
            this.userService = userService;
        }

        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Register(User user)
        {
            if (!ModelState.IsValid)
            {
                return View(user);
            }
            user.Password = userService.HashPassword(user.Password);
            baseRepository.Create<User>(user);

            return RedirectToAction(nameof(Login));
        }

        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Login(UserViewModel userViewModel)
        {
            string hashedPassword = userService.HashPassword(userViewModel.Password);
            User? userFromDb = this.baseRepository.GetAll<User>()
                                                 .FirstOrDefault(x => (x.Email == userViewModel.Email)
                                                                        && x.Password == hashedPassword);
            if (userFromDb == null)
            {
                ModelState.AddModelError("", "A user with this username or password does not exist.");
                return View(userViewModel);
            }
            HttpContext.Session.SetInt32("UserID", userFromDb.ID);
            HttpContext.Session.SetString("UserEmail", userFromDb.Email);

            return RedirectToAction(nameof(ActivityController.Index), "Activity");
        }

        [Authenticate]
        [HttpGet]
        public IActionResult Logout()
        {
            HttpContext.Session.Remove("UserID");
            HttpContext.Session.Remove("UserEmail");

            return RedirectToAction(nameof(ActivityController.Index), "Activity");
        }
    }
}

TO-DO-List/TO-DO-List/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TO DO List</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TO_DO_List.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TO DO List</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1 position-relative">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Activity" asp-action="Index">Activities</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Categories</a>
                        </li>
                        @if (HttpContextAccessor.HttpContext!.Session.GetInt32("UserID") == null)
                        {
                            <li class="nav-item position-absolute top-0 end-0" style="margin-right: 4%">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Register">Register</a>
                            </li>
                            <li class="nav-item position-absolute top-0 end-0">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Login">Login</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item position-absolute top-0 end-0" style="margin-right: 10%">
                                <p class="nav-link text-dark">Hello, @HttpContextAccessor.HttpContext.Session.GetString("UserEmail")!</p>
                            </li>
                            <li class="nav-item position-absolute top-0 end-0">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Logout">Log out</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - TO DO List
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>